# Generated by Django 4.2 on 2025-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='general_discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
