version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    container_name: db
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: "backend"
    restart: always
    container_name: app
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    command: [ "sh","./start" ]

  redis:
    image: "redis:alpine"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/home/app/web
      - ./media:/home/app/web/media

    command: [ "sh","./start-celery-worker" ]

volumes:
  nginx_conf:
  media_volume:
  postgres_data:
  static_volume:

