# Generated by Django 4.2 on 2025-02-03 21:11

import abstract.models.base
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_general_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Amount discount',
                'verbose_name_plural': 'Amount discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='FixedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Fixed discount',
                'verbose_name_plural': 'Fixed discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Percentage discount',
                'verbose_name_plural': 'Percentage discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='SetDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constrain', models.JSONField()),
            ],
            options={
                'verbose_name': 'Set discount',
                'verbose_name_plural': 'Set discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='when created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='when updated')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='GiftForSetDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constrain', models.JSONField()),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_for_set_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Gift for set discount',
                'verbose_name_plural': 'Gift for set discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='when created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='when updated')),
                ('promo_code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('amount', 'Amount'), ('set', 'Set'), ('additional_product', 'Additional product'), ('gift_for_set', 'Gift for set')], max_length=20)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_subtypes', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='AdditionalProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constrain', models.JSONField()),
                ('for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_product', to='product.product')),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_gift', to='product.product')),
            ],
            options={
                'verbose_name': 'Additional product discount',
                'verbose_name_plural': 'Additional product discounts',
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=django.contrib.postgres.indexes.HashIndex(fields=['code'], name='discount_pr_code_1a8a03_hash'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=django.contrib.postgres.indexes.HashIndex(fields=['promo_code'], name='discount_di_promo_c_b6d19d_hash'),
        ),
    ]
