# Generated by Django 4.2 on 2025-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='promo_code',
            field=models.CharField(default='CGnrJa5Loa7Mj7GYiUbb', max_length=20, unique=True),
        ),
    ]
