# Generated by Django 4.2 on 2025-01-29 17:31

import abstract.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='when created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='when updated')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('ordered', 'Ordered'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created', max_length=255)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('nova_poshta', 'Nova Poshta'), ('nova_poshta_courier', 'Nova Poshta Courier'), ('nova_poshta_self', 'Nova Poshta Self'), ('ukr_poshta', 'Ukr Poshta')], max_length=255)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cashless', 'Cashless'), ('nova_pay', 'Nova Pay'), ('cash_on_delivery', 'Cash on delivery'), ('crypto', 'Crypto')], max_length=255)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['id'],
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='when created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='when updated')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.SmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'verbose_name': 'Cart Product',
                'verbose_name_plural': 'Cart Products',
                'ordering': ['cart', 'product'],
            },
            bases=(models.Model, abstract.models.base.QuerySetExplainMixin),
        ),
    ]
